source 'https://rubygems.org'

rails_version = ENV.fetch('RAILS_VERSION', '6.1.x')
gem 'rails', "~> #{rails_version}"

gem 'bizside', path: '..'

gem 'aws-sdk-s3'
gem 'carrierwave'
gem 'coffee-rails', '~> 4.2'
gem 'fog-aws'
gem 'ipaddress'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'mail', '~> 2.7.1'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'nokogiri'
gem 'redis', '~> 4.0'
gem 'request-log-analyzer'
gem 'resque'
gem 'resque-scheduler', '~> 4.8.0'
gem 'rmagick'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3', '>= 1.3', '< 1.6.0'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'cucumber', '~> 7.1'
end

group :development do
  gem 'spring'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'database_cleaner'
  gem 'minitest', '~> 5.15.0'
  gem 'minitest-rails'
  gem 'minitest-reporters'
  gem 'puma'
  gem 'rails-controller-testing'
  gem 'RedCloth'
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem 'webmock'
end

group :itamae_plugin do
  gem 'itamae-plugin-recipe-selenium'
end
