name: Ruby CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7]
        rails-version: [5.2.x, 6.1.x]
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
      CONFIG_FILE: ./config/bizside.yml

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libsqlite3-dev libmagic-dev libmagick++-dev
          sudo apt clean all
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install gem
        run: bundle exec rake install
      - name: Set up test app
        run: bundle install -j4
        working-directory: ./bizside_test_app
      - name: Run tests
        run: rails test
        working-directory: ./bizside_test_app
