name: Ruby CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Prepare for test
        run: sudo mkdir -p /data/ && sudo chmod 777 /data/
      - name: Install gem
        run: bundle exec rake install
      - name: Set up test app
        run: bundle install -j2
        working-directory: ./bizside_test_app
      - name: Run tests
        run: bundle exec rake test CONFIG_FILE=bizside_test_app/config/bizside.yml
